// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoItem.Data;

#nullable disable

namespace ToDoItem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250212185900_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoItem.Models.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("toDoLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeadLine = new DateTime(2025, 2, 19, 20, 58, 59, 804, DateTimeKind.Local).AddTicks(4050),
                            Description = "Practice basic and advanced C# concepts",
                            Title = "Learn C#"
                        },
                        new
                        {
                            Id = 2,
                            DeadLine = new DateTime(2025, 2, 26, 20, 58, 59, 804, DateTimeKind.Local).AddTicks(4134),
                            Description = "Create a To-Do List web app using ASP.NET Core",
                            Title = "Build ASP.NET App"
                        },
                        new
                        {
                            Id = 3,
                            DeadLine = new DateTime(2025, 3, 5, 20, 58, 59, 804, DateTimeKind.Local).AddTicks(4140),
                            Description = "Connect the To-Do List app with a SQL database",
                            Title = "Database Integration"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
